site_name: Python Course
site_url: https://www.hramian.com/python/
site_description: Python Programming for Finance Applications

theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Session 1:
      - Overview: session-1/index.md
      - Foundations of Programming: session-1/p101.md
      - Python Language: session-1/p102.md
      - Python Development Environments: session-1/p103.md
      - Jupyter Notebook: session-1/p104.md
      - Cells and Executing Code: session-1/p105.md
      - Print Statement: session-1/p106.md
      - Setting Variables: session-1/p107.md
      - Mathematical Operators: session-1/p108.md
      - Function: session-1/p109.md
      - Loops: session-1/p110.md
      - Virtual Environment: session-1/p111.md
      - Comments: session-1/p112.md
      - Python Documentation: session-1/p113.md
      - Summary: session-1/p114.md
  - Session 2:
      - Overview: session-2/index.md
      - Variable Assignment: session-2/p201.md
      - Data Types: session-2/p202.md
      - Numpy, Basics: session-2/p203.md
      - Numpy, Random Numbers: session-2/p204.md
      - Numpy, Statistics: session-2/p205.md
      - Numpy, Matrices: session-2/p206.md
      - Pandas, Basics: session-2/p207.md
      - Pandas, Data Examination: session-2/p208.md
      - Pandas, DataFrame Processing: session-2/p209.md
      - Pandas, Essential Tools: session-2/p210.md
      - Summary: session-2/p211.md
  - Session 3:
      - Overview: session-3/index.md
      - Creating DataFrames: session-3/p301.md
      - Importing Data: session-3/p302.md
      - Preparing Data: session-3/p303.md
      - Data Analysis: session-3/p304.md
      - Data Inspection: session-3/p305.md
      - Merging Datasets: session-3/p306.md
  - Session 4:
      - Overview: session-4/index.md
      - Data Insights: session-4/p401.md
      - Visualisation Matters: session-4/p402.md
      - Matplotlib: session-4/p403.md
      - Trends: session-4/p404.md
      - Data Breakdowns: session-4/p405.md
      - Relationships and Distributions: session-4/p406.md


markdown_extensions:
  - tables
  - fenced_code
  - admonition
  - toc:
      permalink: true

extra:
  generator: false

copyright: Copyright &copy; 2026 Hormoz Ramian
site_author: Hormoz Ramian

plugins:
  - search